# Role only tested with one control plane and more nodes
# this is fine with what is requested from the captsone
- name: Kubernetes setup
  become: true
  hosts:
    - c_planes
    - nodes
  vars:
    home_dir: "/home/{{ansible_ssh_user}}"
    kubernetes_version: 1.25
    kubernetes_join_command_extra_opts: "--ignore-preflight-errors=all"
    containerd_config_cgroup_driver_systemd: true
    kubernetes_allow_pods_on_control_plane: false # control plane will be tainted
    kubernetes_pod_network: # Use Calico CNI. The default is Flannel
      cni: 'calico'
      cidr: '192.168.0.0/16'

  roles:
    - geerlingguy.containerd
    - geerlingguy.kubernetes
  tasks:
    - name: ETCD backup cron job
      ansible.builtin.include_tasks:
        file: ./tasks/etcd-backup.yml
      when: kubernetes_role == "control_plane"
    - name: Install metrics server
      ansible.builtin.include_tasks:
        file: ./tasks/metrics-server.yml
      when: kubernetes_role == "control_plane"
