- name: Install etcd client
  ansible.builtin.apt:
    name:
      - etcd-client
    state: present
- name: Copy job to control plane
  ansible.builtin.copy:
    src: "./etcd-snap.sh"
    dest: "{{home_dir}}/.etcd-backup.sh"
    mode: 0555
- name: Setup cron job for etcd backup
  ansible.builtin.cron:
    name: etcd backup
    hour: "23"
    minute: "45"
    job: "{{home_dir}}/.etcd-backup.sh"
