- name: Create namespace easypay
  become: false
  command: "kubectl create ns {{ namespace }}"
  when: create_namespace == true

- name: Download metrics server manifest
  become: false
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    dest: "{{ home_dir }}/metrics-server.yaml"
    mode: 0644

- name: Apply metrics-server manifest to the cluster
  become: false
  command: "kubectl apply -f {{ home_dir }}/metrics-server.yaml"

- name: download metrics server patch
  become: false
  ansible.builtin.get_url:
    url: https://gist.githubusercontent.com/initcron/1a2bd25353e1faa22a0ad41ad1c01b62/raw/008e23f9fbf4d7e2cf79df1dd008de2f1db62a10/k8s-metrics-server.patch.yaml
    dest: "{{ home_dir }}/k8s-metrics-server.patch.yaml"
    mode: 0644
- name: Store patch output
  ansible.builtin.command: "cat {{ home_dir }}/k8s-metrics-server.patch.yaml"
  register: patch

- name: Apply metrics server patch
  become: false
  command: "kubectl patch deploy metrics-server -p {{ patch | quote }} -n kube-system"
